spectaql:
  logoFile: ./test/fixtures/logo.png
  faviconFile: ./test/fixtures/favicon.png
  displayAllServers: true

introspection:
  removeTrailingPeriodFromDescriptions: false
  metadataFile: ./data/metadata.json
  dynamicExamplesProcessingModule: ./customizations/examples
  schemaFile: [./data/schemas/*.graphqls]
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2
  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: GraphQL API Reference
  description: Welcome to the party!
  termsOfService: https://www.example.com/terms
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-introItems:
    - title: Important thing 1
      description: Some important stuff we wanted you to know. Supports `markdown`

servers:
  - url: http://localhost:1010/
    description: Local
#  - url: https://localhost.1010/graphql
#    description: Production
#    production: true
#    headers:
#      - name: Authorization
#        example: Bearer <YOUR_TOKEN_HERE>
#        comment: Your foo from bar
