const handbook = [
  {
    type: 'doc',
    id: 'index'
  },
  {
    type: 'category',
    label: 'Hiring process',
    items: [
      {
        type: 'autogenerated',
        dirName: 'hiring-process',
      },
    ],
  },
  {
    type: 'category',
    label: 'Working here',
    items: [
      {
        type: 'autogenerated',
        dirName: 'working-here',
      },
    ],
  },
  {
    type: 'category',
    label: 'About Openline',
    items: [
      {
        type: 'autogenerated',
        dirName: 'about',
      },
    ],
  },
  {
    type: 'category',
    label: 'How we work',
    items: [
      {
        type: 'autogenerated',
        dirName: 'how-we-work',
      },
    ],
  },
  {
    type: 'category',
    label: 'How we communicate',
    items: [
      {
        type: 'autogenerated',
        dirName: 'how-we-communicate',
      },
    ],
  },
  {
    type: 'doc',
    id: 'contribute'
  },
  {
    type: 'doc',
    id: 'thanks'
  },
]

module.exports = {
  handbook
}