const guides = [
  {
    type: 'doc',
    id: 'index'
  },
  {
    type: 'doc',
    id: 'connector-catalog'
  },
  {
    type: 'category',
    label: 'Connectors',
    items: [
      {
        type: 'autogenerated',
        dirName: 'connectors',
      },
    ],
  },
  {
    type: 'doc',
    id: 'contribute'
  },
]

module.exports = {
  guides
}