const handbook = [
  {
    type: 'doc',
    id: 'index'
  },
  {
    type: 'category',
    label: 'Openline',
    items: [
      {
        type: 'autogenerated',
        dirName: 'openline',
      },
    ],
  },
  {
    type: 'doc',
    id: 'strategy'
  },
  {
    type: 'doc',
    id: 'business-model'
  },
  {
    type: 'category',
    label: 'How we work',
    items: [
      {
        type: 'autogenerated',
        dirName: 'how-we-work',
      },
    ],
  },
  {
    type: 'category',
    label: 'People',
    items: [
      {
        type: 'autogenerated',
        dirName: 'people',
      },
    ],
  },
  {
    type: 'doc',
    id: 'thanks'
  },
]

module.exports = {
  handbook
}