name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - otter
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} \
          --build-env REACT_APP_SP_API_KEY=nobody-will-guess-this-api-key \ 
          --build-env REACT_APP_SP_HTTP_PATH=https://oasis-channels-api.openline.ninja/api/v1 \ 
          --build-env REACT_APP_SP_WS_PATH=wss://oasis-channels-api.openline.ninja/api/v1

        env:
          NODE_AUTH_TOKEN: ${{secrets.REPOSITORY_READ_WRITE_TOKEN}}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
